version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/vhost/:/etc/nginx/vhost.d:ro
      - ./nginx/conf.d/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
      - ./static/:/code/static/
      - ./media/:/code/media/

  postgres:
    image: postgres
    volumes:
      - ./postgresdb/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'trip_db_name'
      POSTGRES_USER: 'trip_user_name'
      POSTGRES_PASSWORD: '123'

  web:
    build: .
    restart: "always"
    ports:
      - "8000:8000"
    volumes:
      - .:/code/
    depends_on:
      - "postgres"
    env_file: ./.env
    container_name: web
  
  pgadmin :
    container_name : pgadmin
    image : dpage/pgadmin4:4.23
    ports: 
      - "5050:80"
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: 'agil@mail.ru'
      PGADMIN_DEFAULT_PASSWORD: '12345'
    
  # celery: 
  #   build: 
  #     context: .
  #     dockerfile: celery.dockerfile
  #   volumes:
  #     - .:/code
  #   links:
  #     # - redis
  #     - postgres
  #   depends_on: 
  #     # - "redis"
  #     - "postgres"
  #   env_file: ./.env

  redis:
    image: redis
    ports:
      - "6379:6379"
    # command: redis-server --requirepass $REDIS_PASSWORD
    restart: "always"
    # env_file: ./.env
